# Generated by Django 6.0.6 on 2026-06-13 17:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Must contain only uppercase letters and digits, between 5 and 50 characters.', regex='^[A-Z0-9]{5,50}$')])),
                ('iban_number', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Must contain only uppercase letters and digits, between 5 and 50 characters.', regex='^[A-Z0-9]{5,50}$')])),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current')], default='current', max_length=20)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='vendor.vendor')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
